name: 1thought.ca
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32122
title: 1thought.ca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70458791-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a5b83'
    - '#01428a'
    - '#0077b5'
    - '#1ab7ea'
    - '#55acee'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
