name: 1thought.ca
favicon: null
layout_spectrum: 0.5938115653116256
typography_spectrum: 0.8843900277279317
title: 1thought.ca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70458791-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#cdc7a5'
    - '#403329'
    - '#130000'
    - '#3879bb'
  brandStrength: 0.75
  lightness: 0.3174694827757776
  saturation: 0.6415469334460795
  rhythmicContrast: 0.8312337007373571
purpose: []
